version: '3.8'
services:
  spring-app:
    container_name: spring-app
    image: rparias/springtest:v${BUILD_NUMBER}
    networks:
      - internal-network
    environment:
      - USER_DB=springstudent
      - PASSWORD_DB=springstudent
      - HOST=localhost
    ports:
      - 8080:8080
    command:
      [
        './wait-for-mysqldb.sh',
        'mysqldb:3306',
        '-t',
        '6000',
        '--',
        'java',
        '-jar',
        './demo-apirest-0.0.1-SNAPSHOT.jar',
      ]
networks:
  internal-network:
# docker exec -i mysqldb sh -c 'exec mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' < $PWD/script.sql
