version: '3.8'
services:
  spring-app:
    container_name: spring-app
    image: rparias/springtest:${BUILD_NUMBER}
    environment:
      - USER_DB=$USER_DB
      - PASSWORD_DB=$PASSWORD_DB
      - HOST=$HOST
    ports:
      - 8080:8080
    command:
      [
        'java',
        '-jar',
        './demo-apirest-0.0.1-SNAPSHOT.jar',
      ]
# docker exec -i mysqldb sh -c 'exec mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD"' < $PWD/script.sql
