version: 2.1

branch-master-filter: &branch-master-filter
  branches:
    only: /main/
  tags:
    ignore: /.*/

orbs:
  docker: circleci/docker@1.5.0

workflows:
  dev-release:
    jobs:
      - build-jar:
          name: Build Jar
          filters: *branch-master-filter
      - docker/publish:
          name: Build and deploy image to docker
          filters: *branch-master-filter
          context:
            - docker-hub-context
          image: rparias/springtest
          dockerfile: /home/circleci/project/demo-apirest-crud/Dockerfile
          requires:
            - Build Jar

jobs:
  build-jar:
    working_directory: ~/demoSpringRestDocker/demo-apirest-crud
    docker:
      - image: maven
    steps:
      - checkout:
          path: ~/demoSpringRestDocker
      - run:
          name: Install Dependencies
          command: |
            mvn -v
            mvn clean install
            ls -la target/