version: 2.1

branch-master-filter: &branch-master-filter
  branches:
    only: /main/
  tags:
    ignore: /.*/

orbs:
  docker: circleci/docker@1.5.0

workflows:
  dev-release:
    jobs:
      - build-jar:
          name: Build Jar
          filters: *branch-master-filter

jobs:
  build-jar:
    working_directory: ~/demoSpringRestDocker/demo-apirest-crud
    docker:
      - image: maven
    steps:
      - checkout:
          path: ~/demoSpringRestDocker
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: Install Dependencies
          command: |
            mvn -v
            mvn clean install
            ls -la target/
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker login --username ${USERNAME} --password ${PASSWORD}
            docker push rparias/springtest:v${TAG}