version: 2.1

branch-master-filter: &branch-master-filter
  branches:
    only: /main/
  tags:
    ignore: /.*/

orbs:
  docker: circleci/docker@1.5.0

workflows:
  dev-release:
    jobs:
      - build-jar:
          name: Build Jar
          filters: *branch-master-filter
          context:
            - docker-hub-context

jobs:
  build-jar:
    working_directory: ~/demoSpringRestDocker/demo-apirest-crud
    docker:
      - image: cimg/openjdk:14.0
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout:
          path: ~/demoSpringRestDocker
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Install Dependencies
          command: |
            mvn -v
            mvn clean install
            ls -la target/
      - run:
          name: Build Docker Image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t rparias/springtest:v$TAG .
            docker push rparias/springtest:v${TAG}