version: 2.1

branch-master-filter: &branch-master-filter
  branches:
    only: /main/
  tags:
    ignore: /.*/

orbs:
  docker: circleci/docker@1.5.0

workflows:
  dev-release:
    jobs:
      - build-jar:
          name: Build Jar
          filters: *branch-master-filter

jobs:
  build-jar:
    working_directory: ~/demoSpringRestDocker/demo-apirest-crud
    docker:
      - image: maven
    steps:
      - checkout:
          path: ~/demoSpringRestDocker
      - run:
          name: Install Dependencies
          command: |
            mvn -v
            mvn clean install
            ls -la target/
      - docker/install-docker
      - docker/build:
          dockerfile: demo-apirest-crud/Dockerfile
          image: rparias/springtest
      - docker/push:
          image: rparias/springtest